version: '3.9'

services:
  
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: hackathon
      POSTGRES_PASSWORD: hackathon
    expose:
      - "5433"
    ports:
      - "5433:5432"
  
  redis:
    container_name: redis
    image: bitnami/redis:latest
    environment:
     - REDIS_PASSWORD=redis
    expose:
      - "9379"
    ports:
      - '9379:6379'
        
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    ports:
      - "5676:5672"
      - "15676:15672"

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2021-09-15T04-54-25Z.hotfix.908b0f10a
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /data
    volumes:
      - ./minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"