version: '3.9'

services:

  postgres:
    container_name: hackathon_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: hackathon
      POSTGRES_PASSWORD: hackathon
    expose:
      - "5433"
    ports:
      - "5433:5432"

  redis:
    container_name: hackathon_redis
    image: bitnami/redis:latest
    environment:
     - REDIS_PASSWORD=redis
    expose:
      - "9379"
    ports:
      - '9379:6379'

  rabbitmq:
    container_name: hackathon_rabbitmq
    image: rabbitmq:3.8-management-alpine
    ports:
      - "5676:5672"
      - "15676:15672"

  minio:
    container_name: hackathon_minio
    image: minio/minio:RELEASE.2021-09-15T04-54-25Z.hotfix.908b0f10a
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /data
    volumes:
      - ./docker/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  grafana:
    container_name: hackathon_grafana
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/provisioning/dashboards/hackathon.json
    volumes:
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"

  loki:
    container_name: hackathon_loki
    image: grafana/loki:2.8.2
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  prometheus:
    container_name: hackathon_prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"