<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="Backend.Tools.Common" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
      <PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Hackathon.Common\Hackathon.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>
