<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hackathon.Common\Hackathon.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
</Project>
