name: Deploy API

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '6.0.x' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Restore dependencies, Build, Publish
      run: |
        dotnet restore
        dotnet build --no-restore --configuration Release
        dotnet publish -c Release -o hackathon_api

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
        
    - name: Install rsync
      run: sudo apt-get install -y rsync
        
    - name: Stop Hackathon.Api
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}
        script: |
          sudo systemctl stop ${{ secrets.DEPLOY_SERVICE_NAME }}
        
    - name: Deploy Hackathon.Api
      run: rsync -avz -e 'ssh' hackathon_api/* ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/var/www/hackathon.api/
          
    - name: Start Hackathon.Api
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}
        script: |
          sudo systemctl start ${{ secrets.DEPLOY_SERVICE_NAME }}