name: .NET

on:
  push:
    branches:
      - develop

  pull_request:
    branches: [ "feature/*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '6.0.x' ]

    services:
      database_tests:
        image: 'postgres'
        env:
          POSTGRES_USER: hackathon
          POSTGRES_PASSWORD: hackathon
          POSTGRES_DB: Hackathon.Tests
        ports:
          - 5433:5432

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Update database
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        dotnet ef database update -p Hackathon.DAL -s Hackathon.API
      env:
        ASPNETCORE_ENVIRONMENT: Tests
    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        ASPNETCORE_ENVIRONMENT: Tests
